version: "2"
services:
  beta-mautic:
    container_name: beta-mautic
    restart: unless-stopped
    image: mautic/mautic
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:80:80"
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=mauticdbpass
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
      - PHP_INI_DATE_TIMEZONE=UTC
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_UPLOAD=30M
      - PHP_MAX_EXECUTION_TIME=300
      - MAUTIC_RUN_CRON_JOBS=true
    volumes:
      - ./production-site:/var/www/html

  mysql:
    restart: unless-stopped
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
    volumes:
      - ./mysql:/var/lib/mysql

  webserver:
    restart: unless-stopped
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/beta-mautic.thrivebrokers.com:/etc/letsencrypt/live/beta-mautic.thrivebrokers.com
      - /docker-volumes/etc/letsencrypt/archive/beta-mautic.thrivebrokers.com:/etc/letsencrypt/archive/beta-mautic.thrivebrokers.com
    depends_on:
      - beta-mautic