name: Build and publish docker container image netresearch/mautic

on:
  push:
    branches:
      - master

jobs:
  push_v303_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic3/apache
          --build-arg MAUTIC_SHA1=720bf3bdf76d404b6ec773c14788d2f68b1e77cc
          --build-arg MAUTIC_VERSION=3.3.2
          --build-arg PHP_VERSION=7.4
          --file mautic3/apache/Dockerfile
          --tag ghcr.io/netresearch/mautic:3.3.2-apache

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ghcr.io/netresearch/mautic:3.3.2-apache ghcr.io/netresearch/mautic:3.3-apache
          docker tag ghcr.io/netresearch/mautic:3.3.2-apache ghcr.io/netresearch/mautic:3-apache
          docker push ghcr.io/netresearch/mautic:3.3.2-apache
          docker push ghcr.io/netresearch/mautic:3.3-apache
          docker push ghcr.io/netresearch/mautic:3-apache

  push_v302_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic3/apache
          --build-arg MAUTIC_SHA1=f57071c500fcedd2a64c0e7b94f0354cfa54d0aa
          --build-arg MAUTIC_VERSION=3.2.5
          --build-arg PHP_VERSION=7.4
          --file mautic3/apache/Dockerfile
          --tag ghcr.io/netresearch/mautic:3.2.5-apache

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ghcr.io/netresearch/mautic:3.2.5-apache ghcr.io/netresearch/mautic:3.2-apache
          docker push ghcr.io/netresearch/mautic:3.2.5-apache
          docker push ghcr.io/netresearch/mautic:3.2-apache

  push_v301_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic3/apache
          --build-arg MAUTIC_SHA1=291ebabd2f12a0d8eced65a0adaa597db8371a39
          --build-arg MAUTIC_VERSION=3.1.2
          --build-arg PHP_VERSION=7.3
          --file mautic3/apache/Dockerfile
          --tag ghcr.io/netresearch/mautic:3.1.2-apache

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ghcr.io/netresearch/mautic:3.1.2-apache ghcr.io/netresearch/mautic:3.1-apache
          docker push ghcr.io/netresearch/mautic:3.1.2-apache
          docker push ghcr.io/netresearch/mautic:3.1-apache

  push_v300_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic3/apache
          --build-arg MAUTIC_SHA1=291ebabd2f12a0d8eced65a0adaa597db8371a39
          --build-arg MAUTIC_VERSION=3.0.2
          --build-arg PHP_VERSION=7.3
          --file mautic3/apache/Dockerfile
          --tag ghcr.io/netresearch/mautic:3.0.2-apache

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ghcr.io/netresearch/mautic:3.0.2-apache ghcr.io/netresearch/mautic:3.0-apache
          docker push ghcr.io/netresearch/mautic:3.0.2-apache
          docker push ghcr.io/netresearch/mautic:3.0-apache

  push_v3_fpm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic3/fpm
          --file mautic3/fpm/Dockerfile
          --tag ghcr.io/netresearch/mautic:3-fpm
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:3-fpm

  push_v2_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic2/apache
          --file mautic2/apache/Dockerfile
          --tag ghcr.io/netresearch/mautic:2-apache
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:2-apache

  push_v2_fpm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: >
          docker buildx build mautic2/fpm
          --file mautic2/fpm/Dockerfile
          --tag ghcr.io/netresearch/mautic:2-fpm
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:2-fpm
