name: Build and publish docker container image netresearch/mautic

on:
  push:
    branches:
      - master

jobs:
  push_v3_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build mautic3/apache --file mautic3/apache/Dockerfile --tag ghcr.io/netresearch/mautic:3-apache
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:3-apache

  push_v3_fpm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build mautic3/fpm --file mautic3/fpm/Dockerfile --tag ghcr.io/netresearch/mautic:3-fpm
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:3-fpm

  push_v2_apache:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build mautic2/apache --file mautic2/apache/Dockerfile --tag ghcr.io/netresearch/mautic:2-apache
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:2-apache

  push_v2_fpm:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build mautic2/fpm --file mautic2/fpm/Dockerfile --tag ghcr.io/netresearch/mautic:2-fpm
        
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/netresearch/mautic:2-fpm
